### ISSUE TITLE
How do you test vue component in Vue on Rails?

### ISSUE THREAD

**Issue by navjeetc** [ytbryan/vuejs#10]
In my erb I am calling a component department like 
```<%= vue_component, 'department', name: @department.name %>```

How to test *department* component? Currently my jest test fails saying "erb is not defined". Is there any way to mock the call to *erb* function?

**Comment by ytbryan** [comment]
Hi @navjeetc, thanks for your questions. Do you have your repo somewhere?

**Comment by ytbryan** [comment]
Without looking at your repo, Jest test with erb is not supported. 

However, if you are looking to have Jest test configuration out-of-the-box, try the application template: 

`rails new app -m http://vueonrails.com/vue`

Once Jest is supported, please run `yarn test` at your root project.

**Comment by navjeetc** [comment]
Well jest is working for other Vue components that do not use _erb_. I do not have a repo but I will try to post a snippet.

**Comment by navjeetc** [comment]
So in this case my _department.vue_ file has _data_ function as below:
```
data: function() {
   return {
     name: erb('name')
    }    
}
```
But when I run jest, it cannot find _erb_ when I call `shallowMount(App).` Since erb is defined in _vue-on-rails.js_ which is not accessible as it is in the gem.

**Comment by ytbryan** [comment]
Hi @navjeetc 

As mentioned at #12, you can use the Webpack's Vue on Rails helper inside your Jest Test. 

```javascript
import {erb} from 'vueonrails'
```

However, the `erb` depends on Rails view to work. Since Jest Test don't load Rails view, `erb` will return an empty string when called inside the Jest Test. 

---

If you want a permanent solution, may I suggest using RSpec as your system tests? Which loads Rails View as default during the tests.

Hope I helped!

**Comment by navjeetc** [comment]
Thanks
